---
name: manual-1

on:
  workflow_dispatch:
  workflow_call:

jobs:
  message:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: message
      uses: actions/github-script@v6
      id: set-result
      with:
        script: return "manual-1 „ÅÆ Actions"
        result-encoding: string
