---
name: manual-2

on:
  workflow_dispatch:

jobs:
  message:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: message
      uses: actions/github-script@v6
      id: set-result
      with:
        script: return "manual-2 „ÅÆ Actions"
        result-encoding: string
